
################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import QCoreApplication, QMetaObject, QRect, QSize
from PySide6.QtGui import QFont
from PySide6.QtWidgets import (
    QFrame,
    QLabel,
    QLineEdit,
    QProgressBar,
    QPushButton,
    QSizePolicy,
    QStatusBar,
    QTabWidget,
    QWidget,
)


class Ui_mainwind:
    def setupUi(self, mainwind):
        if not mainwind.objectName():
            mainwind.setObjectName("mainwind")
        mainwind.resize(345, 380)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainwind.sizePolicy().hasHeightForWidth())
        mainwind.setSizePolicy(sizePolicy)
        mainwind.setMinimumSize(QSize(345, 380))
        mainwind.setMaximumSize(QSize(385, 380))
        font = QFont()
        font.setFamilies(["Inter"])
        font.setPointSize(8)
        mainwind.setFont(font)
        self.centwdgt = QWidget(mainwind)
        self.centwdgt.setObjectName("centwdgt")
        sizePolicy.setHeightForWidth(self.centwdgt.sizePolicy().hasHeightForWidth())
        self.centwdgt.setSizePolicy(sizePolicy)
        self.centwdgt.setMinimumSize(QSize(345, 360))
        self.centwdgt.setMaximumSize(QSize(345, 360))
        self.mainwdgt = QTabWidget(self.centwdgt)
        self.mainwdgt.setObjectName("mainwdgt")
        self.mainwdgt.setGeometry(QRect(5, 80, 335, 245))
        sizePolicy.setHeightForWidth(self.mainwdgt.sizePolicy().hasHeightForWidth())
        self.mainwdgt.setSizePolicy(sizePolicy)
        self.mainwdgt.setMinimumSize(QSize(335, 245))
        self.mainwdgt.setMaximumSize(QSize(335, 245))
        self.mainwdgt.setStyleSheet("font: 8pt \"Inter\";")
        self.mainwdgt.setTabShape(QTabWidget.Rounded)
        self.dlvrwtab = QWidget()
        self.dlvrwtab.setObjectName("dlvrwtab")
        sizePolicy.setHeightForWidth(self.dlvrwtab.sizePolicy().hasHeightForWidth())
        self.dlvrwtab.setSizePolicy(sizePolicy)
        self.dlvrwtab.setMinimumSize(QSize(330, 235))
        self.dlvrwtab.setMaximumSize(QSize(330, 235))
        self.dlvr_line_file = QLineEdit(self.dlvrwtab)
        self.dlvr_line_file.setObjectName("dlvr_line_file")
        self.dlvr_line_file.setGeometry(QRect(5, 60, 320, 25))
        sizePolicy.setHeightForWidth(self.dlvr_line_file.sizePolicy().hasHeightForWidth())
        self.dlvr_line_file.setSizePolicy(sizePolicy)
        self.dlvr_line_file.setMinimumSize(QSize(320, 25))
        self.dlvr_line_file.setMaximumSize(QSize(320, 25))
        self.dlvr_line_file.setStyleSheet("font: 8pt \"Inter\";")
        self.dlvr_line_file.setReadOnly(True)
        self.dlvr_line_file.setClearButtonEnabled(True)
        self.dlvr_line_pswd = QLineEdit(self.dlvrwtab)
        self.dlvr_line_pswd.setObjectName("dlvr_line_pswd")
        self.dlvr_line_pswd.setGeometry(QRect(5, 90, 320, 25))
        sizePolicy.setHeightForWidth(self.dlvr_line_pswd.sizePolicy().hasHeightForWidth())
        self.dlvr_line_pswd.setSizePolicy(sizePolicy)
        self.dlvr_line_pswd.setMinimumSize(QSize(320, 25))
        self.dlvr_line_pswd.setMaximumSize(QSize(320, 25))
        self.dlvr_line_pswd.setStyleSheet("font: 8pt \"Inter\";")
        self.dlvr_line_pswd.setClearButtonEnabled(True)
        self.dlvr_butn_browse = QPushButton(self.dlvrwtab)
        self.dlvr_butn_browse.setObjectName("dlvr_butn_browse")
        self.dlvr_butn_browse.setGeometry(QRect(70, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.dlvr_butn_browse.sizePolicy().hasHeightForWidth())
        self.dlvr_butn_browse.setSizePolicy(sizePolicy)
        self.dlvr_butn_browse.setMinimumSize(QSize(60, 25))
        self.dlvr_butn_browse.setMaximumSize(QSize(60, 25))
        self.dlvr_butn_browse.setStyleSheet("font: 8pt \"Inter\";")
        self.dlvr_butn_random = QPushButton(self.dlvrwtab)
        self.dlvr_butn_random.setObjectName("dlvr_butn_random")
        self.dlvr_butn_random.setGeometry(QRect(135, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.dlvr_butn_random.sizePolicy().hasHeightForWidth())
        self.dlvr_butn_random.setSizePolicy(sizePolicy)
        self.dlvr_butn_random.setMinimumSize(QSize(60, 25))
        self.dlvr_butn_random.setMaximumSize(QSize(60, 25))
        self.dlvr_butn_random.setStyleSheet("font: 8pt \"Inter\";")
        self.dlvr_line_size = QLineEdit(self.dlvrwtab)
        self.dlvr_line_size.setObjectName("dlvr_line_size")
        self.dlvr_line_size.setGeometry(QRect(5, 30, 320, 25))
        sizePolicy.setHeightForWidth(self.dlvr_line_size.sizePolicy().hasHeightForWidth())
        self.dlvr_line_size.setSizePolicy(sizePolicy)
        self.dlvr_line_size.setMinimumSize(QSize(320, 25))
        self.dlvr_line_size.setMaximumSize(QSize(320, 25))
        self.dlvr_line_size.setStyleSheet("font: 8pt \"Inter\";")
        self.dlvr_line_size.setClearButtonEnabled(True)
        self.dlvr_butn_normal = QPushButton(self.dlvrwtab)
        self.dlvr_butn_normal.setObjectName("dlvr_butn_normal")
        self.dlvr_butn_normal.setGeometry(QRect(200, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.dlvr_butn_normal.sizePolicy().hasHeightForWidth())
        self.dlvr_butn_normal.setSizePolicy(sizePolicy)
        self.dlvr_butn_normal.setMinimumSize(QSize(60, 25))
        self.dlvr_butn_normal.setMaximumSize(QSize(60, 25))
        self.dlvr_butn_normal.setStyleSheet("font: 8pt \"Inter\";")
        self.dlvr_line_endo = QLineEdit(self.dlvrwtab)
        self.dlvr_line_endo.setObjectName("dlvr_line_endo")
        self.dlvr_line_endo.setGeometry(QRect(5, 120, 320, 25))
        sizePolicy.setHeightForWidth(self.dlvr_line_endo.sizePolicy().hasHeightForWidth())
        self.dlvr_line_endo.setSizePolicy(sizePolicy)
        self.dlvr_line_endo.setMinimumSize(QSize(320, 25))
        self.dlvr_line_endo.setMaximumSize(QSize(320, 25))
        self.dlvr_line_endo.setStyleSheet("font: 8pt \"Inter\";")
        self.dlvr_line_endo.setClearButtonEnabled(True)
        self.dlvr_line_time = QLineEdit(self.dlvrwtab)
        self.dlvr_line_time.setObjectName("dlvr_line_time")
        self.dlvr_line_time.setGeometry(QRect(5, 150, 320, 25))
        sizePolicy.setHeightForWidth(self.dlvr_line_time.sizePolicy().hasHeightForWidth())
        self.dlvr_line_time.setSizePolicy(sizePolicy)
        self.dlvr_line_time.setMinimumSize(QSize(320, 25))
        self.dlvr_line_time.setMaximumSize(QSize(320, 25))
        self.dlvr_line_time.setStyleSheet("font: 8pt \"Inter\";")
        self.dlvr_line_time.setClearButtonEnabled(True)
        self.dlvr_horiline_b = QFrame(self.dlvrwtab)
        self.dlvr_horiline_b.setObjectName("dlvr_horiline_b")
        self.dlvr_horiline_b.setGeometry(QRect(5, 180, 320, 2))
        sizePolicy.setHeightForWidth(self.dlvr_horiline_b.sizePolicy().hasHeightForWidth())
        self.dlvr_horiline_b.setSizePolicy(sizePolicy)
        self.dlvr_horiline_b.setMinimumSize(QSize(320, 2))
        self.dlvr_horiline_b.setMaximumSize(QSize(320, 2))
        self.dlvr_horiline_b.setStyleSheet("")
        self.dlvr_horiline_b.setFrameShape(QFrame.Shape.HLine)
        self.dlvr_horiline_b.setFrameShadow(QFrame.Shadow.Sunken)
        self.dlvr_horiline_a = QFrame(self.dlvrwtab)
        self.dlvr_horiline_a.setObjectName("dlvr_horiline_a")
        self.dlvr_horiline_a.setGeometry(QRect(5, 25, 320, 2))
        sizePolicy.setHeightForWidth(self.dlvr_horiline_a.sizePolicy().hasHeightForWidth())
        self.dlvr_horiline_a.setSizePolicy(sizePolicy)
        self.dlvr_horiline_a.setMinimumSize(QSize(320, 2))
        self.dlvr_horiline_a.setMaximumSize(QSize(320, 2))
        self.dlvr_horiline_a.setStyleSheet("")
        self.dlvr_horiline_a.setFrameShape(QFrame.Shape.HLine)
        self.dlvr_horiline_a.setFrameShadow(QFrame.Shadow.Sunken)
        self.dlvr_butn_incept = QPushButton(self.dlvrwtab)
        self.dlvr_butn_incept.setObjectName("dlvr_butn_incept")
        self.dlvr_butn_incept.setGeometry(QRect(265, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.dlvr_butn_incept.sizePolicy().hasHeightForWidth())
        self.dlvr_butn_incept.setSizePolicy(sizePolicy)
        self.dlvr_butn_incept.setMinimumSize(QSize(60, 25))
        self.dlvr_butn_incept.setMaximumSize(QSize(60, 25))
        self.dlvr_butn_incept.setStyleSheet("font: 8pt \"Inter\";")
        self.dlvr_head_file = QLabel(self.dlvrwtab)
        self.dlvr_head_file.setObjectName("dlvr_head_file")
        self.dlvr_head_file.setGeometry(QRect(5, 5, 320, 15))
        sizePolicy.setHeightForWidth(self.dlvr_head_file.sizePolicy().hasHeightForWidth())
        self.dlvr_head_file.setSizePolicy(sizePolicy)
        self.dlvr_head_file.setMinimumSize(QSize(320, 15))
        self.dlvr_head_file.setMaximumSize(QSize(320, 15))
        self.dlvr_head_file.setStyleSheet("font: italic 8pt \"Inter\";")
        self.dlvr_butn_detail = QPushButton(self.dlvrwtab)
        self.dlvr_butn_detail.setObjectName("dlvr_butn_detail")
        self.dlvr_butn_detail.setGeometry(QRect(5, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.dlvr_butn_detail.sizePolicy().hasHeightForWidth())
        self.dlvr_butn_detail.setSizePolicy(sizePolicy)
        self.dlvr_butn_detail.setMinimumSize(QSize(60, 25))
        self.dlvr_butn_detail.setMaximumSize(QSize(60, 25))
        self.dlvr_butn_detail.setStyleSheet("font: 8pt \"Inter\";")
        self.mainwdgt.addTab(self.dlvrwtab, "")
        self.clctwtab = QWidget()
        self.clctwtab.setObjectName("clctwtab")
        sizePolicy.setHeightForWidth(self.clctwtab.sizePolicy().hasHeightForWidth())
        self.clctwtab.setSizePolicy(sizePolicy)
        self.clctwtab.setMinimumSize(QSize(330, 235))
        self.clctwtab.setMaximumSize(QSize(330, 235))
        self.clct_butn_normal = QPushButton(self.clctwtab)
        self.clct_butn_normal.setObjectName("clct_butn_normal")
        self.clct_butn_normal.setGeometry(QRect(200, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.clct_butn_normal.sizePolicy().hasHeightForWidth())
        self.clct_butn_normal.setSizePolicy(sizePolicy)
        self.clct_butn_normal.setMinimumSize(QSize(60, 25))
        self.clct_butn_normal.setMaximumSize(QSize(60, 25))
        self.clct_butn_normal.setStyleSheet("font: 8pt \"Inter\";")
        self.clct_line_file = QLineEdit(self.clctwtab)
        self.clct_line_file.setObjectName("clct_line_file")
        self.clct_line_file.setGeometry(QRect(5, 60, 320, 25))
        sizePolicy.setHeightForWidth(self.clct_line_file.sizePolicy().hasHeightForWidth())
        self.clct_line_file.setSizePolicy(sizePolicy)
        self.clct_line_file.setMinimumSize(QSize(320, 25))
        self.clct_line_file.setMaximumSize(QSize(320, 25))
        self.clct_line_file.setStyleSheet("font: 8pt \"Inter\";")
        self.clct_line_file.setReadOnly(True)
        self.clct_line_file.setClearButtonEnabled(True)
        self.clct_horiline_a = QFrame(self.clctwtab)
        self.clct_horiline_a.setObjectName("clct_horiline_a")
        self.clct_horiline_a.setGeometry(QRect(5, 25, 320, 2))
        sizePolicy.setHeightForWidth(self.clct_horiline_a.sizePolicy().hasHeightForWidth())
        self.clct_horiline_a.setSizePolicy(sizePolicy)
        self.clct_horiline_a.setMinimumSize(QSize(320, 2))
        self.clct_horiline_a.setMaximumSize(QSize(320, 2))
        self.clct_horiline_a.setStyleSheet("")
        self.clct_horiline_a.setFrameShape(QFrame.Shape.HLine)
        self.clct_horiline_a.setFrameShadow(QFrame.Shadow.Sunken)
        self.clct_line_pswd = QLineEdit(self.clctwtab)
        self.clct_line_pswd.setObjectName("clct_line_pswd")
        self.clct_line_pswd.setGeometry(QRect(5, 90, 320, 25))
        sizePolicy.setHeightForWidth(self.clct_line_pswd.sizePolicy().hasHeightForWidth())
        self.clct_line_pswd.setSizePolicy(sizePolicy)
        self.clct_line_pswd.setMinimumSize(QSize(320, 25))
        self.clct_line_pswd.setMaximumSize(QSize(320, 25))
        self.clct_line_pswd.setStyleSheet("font: 8pt \"Inter\";")
        self.clct_line_pswd.setClearButtonEnabled(True)
        self.clct_butn_random = QPushButton(self.clctwtab)
        self.clct_butn_random.setObjectName("clct_butn_random")
        self.clct_butn_random.setGeometry(QRect(135, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.clct_butn_random.sizePolicy().hasHeightForWidth())
        self.clct_butn_random.setSizePolicy(sizePolicy)
        self.clct_butn_random.setMinimumSize(QSize(60, 25))
        self.clct_butn_random.setMaximumSize(QSize(60, 25))
        self.clct_butn_random.setStyleSheet("font: 8pt \"Inter\";")
        self.clct_line_endo = QLineEdit(self.clctwtab)
        self.clct_line_endo.setObjectName("clct_line_endo")
        self.clct_line_endo.setGeometry(QRect(5, 120, 320, 25))
        sizePolicy.setHeightForWidth(self.clct_line_endo.sizePolicy().hasHeightForWidth())
        self.clct_line_endo.setSizePolicy(sizePolicy)
        self.clct_line_endo.setMinimumSize(QSize(320, 25))
        self.clct_line_endo.setMaximumSize(QSize(320, 25))
        self.clct_line_endo.setStyleSheet("font: 8pt \"Inter\";")
        self.clct_line_endo.setClearButtonEnabled(True)
        self.clct_butn_incept = QPushButton(self.clctwtab)
        self.clct_butn_incept.setObjectName("clct_butn_incept")
        self.clct_butn_incept.setGeometry(QRect(265, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.clct_butn_incept.sizePolicy().hasHeightForWidth())
        self.clct_butn_incept.setSizePolicy(sizePolicy)
        self.clct_butn_incept.setMinimumSize(QSize(60, 25))
        self.clct_butn_incept.setMaximumSize(QSize(60, 25))
        self.clct_butn_incept.setStyleSheet("font: 8pt \"Inter\";")
        self.clct_horiline_b = QFrame(self.clctwtab)
        self.clct_horiline_b.setObjectName("clct_horiline_b")
        self.clct_horiline_b.setGeometry(QRect(5, 180, 320, 2))
        sizePolicy.setHeightForWidth(self.clct_horiline_b.sizePolicy().hasHeightForWidth())
        self.clct_horiline_b.setSizePolicy(sizePolicy)
        self.clct_horiline_b.setMinimumSize(QSize(320, 2))
        self.clct_horiline_b.setMaximumSize(QSize(320, 2))
        self.clct_horiline_b.setStyleSheet("")
        self.clct_horiline_b.setFrameShape(QFrame.Shape.HLine)
        self.clct_horiline_b.setFrameShadow(QFrame.Shadow.Sunken)
        self.clct_line_time = QLineEdit(self.clctwtab)
        self.clct_line_time.setObjectName("clct_line_time")
        self.clct_line_time.setGeometry(QRect(5, 150, 320, 25))
        sizePolicy.setHeightForWidth(self.clct_line_time.sizePolicy().hasHeightForWidth())
        self.clct_line_time.setSizePolicy(sizePolicy)
        self.clct_line_time.setMinimumSize(QSize(320, 25))
        self.clct_line_time.setMaximumSize(QSize(320, 25))
        self.clct_line_time.setStyleSheet("font: 8pt \"Inter\";")
        self.clct_line_time.setClearButtonEnabled(True)
        self.clct_butn_browse = QPushButton(self.clctwtab)
        self.clct_butn_browse.setObjectName("clct_butn_browse")
        self.clct_butn_browse.setGeometry(QRect(70, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.clct_butn_browse.sizePolicy().hasHeightForWidth())
        self.clct_butn_browse.setSizePolicy(sizePolicy)
        self.clct_butn_browse.setMinimumSize(QSize(60, 25))
        self.clct_butn_browse.setMaximumSize(QSize(60, 25))
        self.clct_butn_browse.setStyleSheet("font: 8pt \"Inter\";")
        self.clct_head_file = QLabel(self.clctwtab)
        self.clct_head_file.setObjectName("clct_head_file")
        self.clct_head_file.setGeometry(QRect(5, 5, 320, 15))
        sizePolicy.setHeightForWidth(self.clct_head_file.sizePolicy().hasHeightForWidth())
        self.clct_head_file.setSizePolicy(sizePolicy)
        self.clct_head_file.setMinimumSize(QSize(320, 15))
        self.clct_head_file.setMaximumSize(QSize(320, 15))
        self.clct_head_file.setStyleSheet("font: italic 8pt \"Inter\";")
        self.clct_line_size = QLineEdit(self.clctwtab)
        self.clct_line_size.setObjectName("clct_line_size")
        self.clct_line_size.setGeometry(QRect(5, 30, 320, 25))
        sizePolicy.setHeightForWidth(self.clct_line_size.sizePolicy().hasHeightForWidth())
        self.clct_line_size.setSizePolicy(sizePolicy)
        self.clct_line_size.setMinimumSize(QSize(320, 25))
        self.clct_line_size.setMaximumSize(QSize(320, 25))
        self.clct_line_size.setStyleSheet("font: 8pt \"Inter\";")
        self.clct_line_size.setReadOnly(True)
        self.clct_line_size.setClearButtonEnabled(True)
        self.clct_butn_detail = QPushButton(self.clctwtab)
        self.clct_butn_detail.setObjectName("clct_butn_detail")
        self.clct_butn_detail.setGeometry(QRect(5, 185, 60, 25))
        sizePolicy.setHeightForWidth(self.clct_butn_detail.sizePolicy().hasHeightForWidth())
        self.clct_butn_detail.setSizePolicy(sizePolicy)
        self.clct_butn_detail.setMinimumSize(QSize(60, 25))
        self.clct_butn_detail.setMaximumSize(QSize(60, 25))
        self.clct_butn_detail.setStyleSheet("font: 8pt \"Inter\";")
        self.mainwdgt.addTab(self.clctwtab, "")
        self.sockaddr = QLineEdit(self.centwdgt)
        self.sockaddr.setObjectName("sockaddr")
        self.sockaddr.setGeometry(QRect(5, 5, 335, 25))
        sizePolicy.setHeightForWidth(self.sockaddr.sizePolicy().hasHeightForWidth())
        self.sockaddr.setSizePolicy(sizePolicy)
        self.sockaddr.setMinimumSize(QSize(335, 25))
        self.sockaddr.setMaximumSize(QSize(335, 25))
        self.sockaddr.setStyleSheet("font: 8pt \"Inter\";")
        self.progbarg = QProgressBar(self.centwdgt)
        self.progbarg.setObjectName("progbarg")
        self.progbarg.setGeometry(QRect(5, 330, 335, 20))
        sizePolicy.setHeightForWidth(self.progbarg.sizePolicy().hasHeightForWidth())
        self.progbarg.setSizePolicy(sizePolicy)
        self.progbarg.setMinimumSize(QSize(335, 20))
        self.progbarg.setMaximumSize(QSize(335, 20))
        self.progbarg.setStyleSheet("font: 8pt \"Inter\";")
        self.progbarg.setValue(0)
        self.progbarg.setTextVisible(True)
        self.head_rqst = QLabel(self.centwdgt)
        self.head_rqst.setObjectName("head_rqst")
        self.head_rqst.setGeometry(QRect(5, 35, 335, 15))
        sizePolicy.setHeightForWidth(self.head_rqst.sizePolicy().hasHeightForWidth())
        self.head_rqst.setSizePolicy(sizePolicy)
        self.head_rqst.setMinimumSize(QSize(335, 15))
        self.head_rqst.setMaximumSize(QSize(335, 15))
        self.head_rqst.setStyleSheet("font: 8pt \"Inter\";")
        self.head_iden = QLabel(self.centwdgt)
        self.head_iden.setObjectName("head_iden")
        self.head_iden.setGeometry(QRect(5, 55, 335, 20))
        sizePolicy.setHeightForWidth(self.head_iden.sizePolicy().hasHeightForWidth())
        self.head_iden.setSizePolicy(sizePolicy)
        self.head_iden.setMinimumSize(QSize(335, 20))
        self.head_iden.setMaximumSize(QSize(335, 20))
        font1 = QFont()
        font1.setFamilies(["Inter"])
        font1.setPointSize(12)
        font1.setBold(False)
        font1.setItalic(False)
        self.head_iden.setFont(font1)
        self.head_iden.setStyleSheet("font: 12pt \"Inter\";")
        mainwind.setCentralWidget(self.centwdgt)
        self.statarea = QStatusBar(mainwind)
        self.statarea.setObjectName("statarea")
        sizePolicy.setHeightForWidth(self.statarea.sizePolicy().hasHeightForWidth())
        self.statarea.setSizePolicy(sizePolicy)
        self.statarea.setMinimumSize(QSize(345, 20))
        self.statarea.setMaximumSize(QSize(345, 20))
        self.statarea.setFont(font)
        self.statarea.setSizeGripEnabled(False)
        mainwind.setStatusBar(self.statarea)

        self.retranslateUi(mainwind)

        self.mainwdgt.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(mainwind)
    # setupUi

    def retranslateUi(self, mainwind):
        mainwind.setWindowTitle(QCoreApplication.translate("mainwind", "MainWindow", None))
        self.dlvr_line_file.setPlaceholderText(QCoreApplication.translate("mainwind", "Filepath for delivering", None))
        self.dlvr_line_pswd.setPlaceholderText(QCoreApplication.translate("mainwind", "Password for delivering", None))
        self.dlvr_butn_browse.setText(QCoreApplication.translate("mainwind", "BROWSE", None))
        self.dlvr_butn_random.setText(QCoreApplication.translate("mainwind", "RANDOM", None))
        self.dlvr_line_size.setText("")
        self.dlvr_line_size.setPlaceholderText(QCoreApplication.translate("mainwind", "Size for processing", None))
        self.dlvr_butn_normal.setText(QCoreApplication.translate("mainwind", "NORMAL", None))
        self.dlvr_line_endo.setText("")
        self.dlvr_line_endo.setPlaceholderText(QCoreApplication.translate("mainwind", "Identifier for locating (Optional)", None))
        self.dlvr_line_time.setText("")
        self.dlvr_line_time.setPlaceholderText(QCoreApplication.translate("mainwind", "Expiry for participants", None))
        self.dlvr_butn_incept.setText(QCoreApplication.translate("mainwind", "INCEPT", None))
        self.dlvr_head_file.setText(QCoreApplication.translate("mainwind", "No location selected", None))
        self.dlvr_butn_detail.setText(QCoreApplication.translate("mainwind", "DETAIL", None))
        self.mainwdgt.setTabText(self.mainwdgt.indexOf(self.dlvrwtab), QCoreApplication.translate("mainwind", "DELIVERING", None))
        self.clct_butn_normal.setText(QCoreApplication.translate("mainwind", "NORMAL", None))
        self.clct_line_file.setPlaceholderText(QCoreApplication.translate("mainwind", "Filepath for collecting", None))
        self.clct_line_pswd.setPlaceholderText(QCoreApplication.translate("mainwind", "Password for collecting", None))
        self.clct_butn_random.setText(QCoreApplication.translate("mainwind", "RANDOM", None))
        self.clct_line_endo.setText("")
        self.clct_line_endo.setPlaceholderText(QCoreApplication.translate("mainwind", "Identifier for locating (Optional)", None))
        self.clct_butn_incept.setText(QCoreApplication.translate("mainwind", "INCEPT", None))
        self.clct_line_time.setText("")
        self.clct_line_time.setPlaceholderText(QCoreApplication.translate("mainwind", "Expiry for participants", None))
        self.clct_butn_browse.setText(QCoreApplication.translate("mainwind", "BROWSE", None))
        self.clct_head_file.setText(QCoreApplication.translate("mainwind", "No location selected", None))
        self.clct_line_size.setText("")
        self.clct_line_size.setPlaceholderText(QCoreApplication.translate("mainwind", "Size for processing", None))
        self.clct_butn_detail.setText(QCoreApplication.translate("mainwind", "DETAIL", None))
        self.mainwdgt.setTabText(self.mainwdgt.indexOf(self.clctwtab), QCoreApplication.translate("mainwind", "COLLECTING", None))
        self.sockaddr.setPlaceholderText(QCoreApplication.translate("mainwind", "Set the address for the service endpoint", None))
        self.head_rqst.setText(QCoreApplication.translate("mainwind", "Please initialize the connection to acquire an identity", None))
        self.head_iden.setText(QCoreApplication.translate("mainwind", "INACCESSIBLE", None))
    # retranslateUi
