---
name: "expedite"
on: ["push"]
jobs:
  ci-build:
    runs-on: "windows-latest"
    strategy:
      fail-fast: false

  steps:
    - name: "Checkout the codebase to a local working directory"
      uses: "actions/checkout@v4"

    - name: "Setup a functioning local Python 3 installation"
      uses: "actions/setup-python@v5"
      with:
        python-version: "3.12"

    - name: "Install the base dependencies"
      run: "python3 -m pip3 install --upgrade poetry pyinstaller"

    - name: "Install the project dependencies"
      run: "python3 -m poetry install"

    - name: "Build the project binary"
      run: "python3 -m pyinstaller expedite\client\bridge\main.py --clean --onefile --name 'ed-bridge-${{ github.sha }}' --windowed --icon assets\icon\expedite.ico"

    - uses: "actions/upload-artifact@v4"
      with:
        path: "dist/*"
